import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

function formatNaira(amount: number, currency: string) {
  const symbol = currency === "NGN" ? "₦" : currency === "GHS" ? "₵" : currency === "KES" ? "Ksh" : currency;
  return `${symbol}${Number(amount).toLocaleString("en-NG", { minimumFractionDigits: 2 })}`;
}

function toCSV(records: Record<string, unknown>[], currency: string): string {
  const header = ["Date", "Type", "Description", "Category", "Amount"].join(",");
  const rows = records.map((r) => [
    r.record_date,
    r.type === "sale" ? "Sale" : "Expense",
    `"${String(r.description ?? "").replace(/"/g, '""')}"`,
    `"${String(r.category ?? "").replace(/"/g, '""')}"`,
    formatNaira(Number(r.amount), currency),
  ].join(","));
  return [header, ...rows].join("\n");
}

function toPrintHTML(
  records: Record<string, unknown>[],
  currency: string,
  startDate: string,
  endDate: string,
  businessName: string,
): string {
  const totalSales    = records.filter(r => r.type === "sale").reduce((s, r) => s + Number(r.amount), 0);
  const totalExpenses = records.filter(r => r.type === "expense").reduce((s, r) => s + Number(r.amount), 0);
  const profit        = totalSales - totalExpenses;

  const rows = records.map((r) => `
    <tr class="${r.type === "sale" ? "sale" : "expense"}">
      <td>${r.record_date}</td>
      <td class="type-badge">${r.type === "sale" ? "Sale" : "Expense"}</td>
      <td>${r.description ?? ""}</td>
      <td>${r.category ?? ""}</td>
      <td class="amount">${formatNaira(Number(r.amount), currency)}</td>
    </tr>`).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>SPAL Export — ${startDate} to ${endDate}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #0F172A; padding: 32px; background: #fff; }
  .header { margin-bottom: 28px; }
  .logo { font-size: 18px; font-weight: 900; letter-spacing: 0.1em; color: #0F172A; margin-bottom: 4px; }
  .logo span { color: #22C55E; }
  .meta { font-size: 13px; color: #64748B; margin-top: 6px; }
  .summary { display: flex; gap: 20px; margin-bottom: 28px; flex-wrap: wrap; }
  .summary-card { flex: 1; min-width: 120px; padding: 14px 16px; border-radius: 10px; background: #F8FAFC; border: 1px solid #E2E8F0; }
  .summary-card .label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #94A3B8; margin-bottom: 4px; }
  .summary-card .value { font-size: 17px; font-weight: 700; }
  .summary-card.green .value { color: #22C55E; }
  .summary-card.orange .value { color: #FF7A00; }
  .summary-card.blue .value { color: #2563EB; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 10px 12px; background: #F1F5F9; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: #64748B; border-bottom: 2px solid #E2E8F0; }
  td { padding: 10px 12px; border-bottom: 1px solid #F1F5F9; vertical-align: middle; }
  tr.sale td { background: #F0FDF4; }
  tr.expense td { background: #FFF7ED; }
  .type-badge { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
  tr.sale .type-badge { color: #22C55E; }
  tr.expense .type-badge { color: #FF7A00; }
  .amount { font-weight: 600; font-variant-numeric: tabular-nums; }
  .footer { margin-top: 24px; font-size: 11px; color: #94A3B8; text-align: center; }
  @media print {
    body { padding: 16px; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
<div class="header">
  <div class="logo">SPAL<span>.</span></div>
  <div class="meta">${businessName} &nbsp;·&nbsp; ${startDate} to ${endDate} &nbsp;·&nbsp; ${records.length} record${records.length !== 1 ? "s" : ""}</div>
</div>

<div class="summary">
  <div class="summary-card green">
    <div class="label">Total Sales</div>
    <div class="value">${formatNaira(totalSales, currency)}</div>
  </div>
  <div class="summary-card orange">
    <div class="label">Total Expenses</div>
    <div class="value">${formatNaira(totalExpenses, currency)}</div>
  </div>
  <div class="summary-card blue">
    <div class="label">Profit</div>
    <div class="value">${formatNaira(profit, currency)}</div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>Description</th>
      <th>Category</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>${rows}</tbody>
</table>

<p class="footer">Generated by SPAL &nbsp;·&nbsp; ${new Date().toLocaleDateString("en-NG", { dateStyle: "long" })}</p>

<script>window.onload = () => window.print();</script>
</body>
</html>`;
}

export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const startDate = searchParams.get("start_date");
    const endDate   = searchParams.get("end_date");
    const format    = searchParams.get("format") ?? "csv"; // csv | pdf

    if (!startDate || !endDate) {
      return NextResponse.json({ error: "start_date and end_date are required" }, { status: 400 });
    }

    // Fetch records in range
    const { data: records, error } = await supabase
      .from("records")
      .select("*")
      .eq("user_id", user.id)
      .gte("record_date", startDate)
      .lte("record_date", endDate)
      .order("record_date", { ascending: false })
      .order("created_at", { ascending: false });

    if (error) throw error;

    // Fetch user profile for currency + business name
    const { data: profile } = await supabase
      .from("users")
      .select("currency, business_name, full_name")
      .eq("id", user.id)
      .single();

    const currency     = profile?.currency ?? "NGN";
    const businessName = profile?.business_name ?? profile?.full_name ?? "My Business";

    if (format === "pdf") {
      const html = toPrintHTML(records ?? [], currency, startDate, endDate, businessName);
      return new NextResponse(html, {
        headers: {
          "Content-Type": "text/html; charset=utf-8",
        },
      });
    }

    // Default: CSV
    const csv      = toCSV(records ?? [], currency);
    const filename = `spal-records-${startDate}-to-${endDate}.csv`;
    return new NextResponse(csv, {
      headers: {
        "Content-Type":        "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    console.error("GET /api/records/export", err);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
